name: Deploy Kotlin App to Internal Testing
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-internal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Sign AAB
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew :app:bundleRelease

      - name: Upload to Internal Track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.ted.desipartygames
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed